Domain = 50
Sequence = ["pdelay_req", "pdelay_resp"]
Count = 3
Interval = 1000
Vlan = 10
Udp = true
Onestep = true

[Ports.veth1]
GM = true
IP = "10.11.0.1"
EgressLatency = 300
IngressLatency = 100

[Ports.veth2]
IP = "10.11.0.2"
EgressLatency = 200
IngressLatency = 150
